
/*
action 类型
 */
// Timeline
export const SWITCH_TIMELINE_SEGMENT = 'SWITCH_TIMELINE_SEGMENT'
export const INVALIDATE_TIMELINE = 'INVALIDATE_TIMELINE'
export const REQUEST_TIMELINE = 'REQUEST_TIMELINE'
export const RECEIVE_TIMELINE = 'RECEIVE_TIMELINE'
export const REQUEST_MORE_TIMELINE = 'REQUEST_MORE_TIMELINE'
export const RECEIVE_MORE_TIMELINE = 'RECEIVE_MORE_TIMELINE'

// 枚举常量
export const TimelineSegments = {
  FAVORITE: 0,
  ALL: 1
}
